# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:android)

platform :android do
  desc "Runs all unit tests"
  lane :test do
    gradle(task: "testDebugUnitTest")
  end

  desc "Build the debug app"
  lane :build do
    gradle(task: "assembleDebug")
  end

  desc "Create release APK"
  lane :release do
    gradle(task: "assembleRelease")
  end

  desc "Clean and assemble release APK"
  lane :beta do
    gradle(task: "clean assembleRelease")
  end
end
